development:
  adapter: postgresql
  encoding: unicode
  database: de0atres_development
  pool: 5
  username: postgres
  password: 123qwe123

test:
  adapter: postgresql
  encoding: unicode
  database: de0atres_test
  pool: 5
  username: postgres
  password: 123qwe123

production:
  adapter: postgresql
  encoding: unicode
  database: de0atres_production
  pool: 5