development:
  adapter: postgresql
  encoding: unicode
  database: nacho_urquiza_development
  pool: 5
  username: postgres
  password: 123qwe123

test:
  adapter: postgresql
  encoding: unicode
  database: nacho_urquiza_test
  pool: 5
  username: postgres
  password: 123qwe123

production:
  adapter: postgresql
  encoding: unicode
  database: nacho_urquiza_production
  pool: 5