# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6eeb3b02f2ccef429796a8be6101b7e08e6fc482c8ca3b97f8c924fcb8eec5397198251d36e3e87d89df8009c30eaf373a4e50ce08f6fb7cf0ada322e72cec86

test:
  secret_key_base: 843902bcfb8bc29e14211d064091cc4006666b221ca208b586c0e3af062717a83e2d942020efb18576cf526cd41a527875417e3f83f08a486bc072720153b93a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
